version: "3.8"

name: "edpn-backend"
services:
  zookeeper:
  ## TODO: Tag this image locally
    image: "bitnami/zookeeper:3.8"
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper:/bitnami"
    healthcheck:
      test: nc -vz localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  kafka:
  ## TODO: Tag this image locally
    image: "bitnami/kafka:3.4"
    restart: on-failure
    env_file:
          - env/${ENVIRONMENT}/.env_kafka
    volumes:
      - "kafka:/bitnami/kafka"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      zookeeper:
        condition: service_healthy

  trademodule_postgis:
    ## TODO: Tag this image locally
    image: "postgis/postgis:15-3.3-alpine"
    restart: on-failure
    env_file:
      - env/${ENVIRONMENT}/.env_trademodule
    volumes:
      - "trademodule_postgis:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d trademodule -U edpn_trademodule"]
      interval: 10s
      timeout: 5s
      retries: 5

  explorationmodule_postgis:
    ## TODO: Tag this image locally
    image: "postgis/postgis:15-3.3-alpine"
    restart: on-failure
    env_file:
      - env/${ENVIRONMENT}/.env_explorationmodule
    volumes:
      - "explorationmodule_postgis:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d explorationmodule -U edpn_explorationmodule"]
      interval: 10s
      timeout: 5s
      retries: 5

  eddn-message-listener:
    image: nexus.edpn.io/edpn/backend/eddn-message-listener:latest-snapshot
    restart: on-failure
    env_file:
      - env/${ENVIRONMENT}/.env_eddn_message_listener
    healthcheck:
      test: "wget -qO- localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      kafka:
        condition: service_healthy

  modulith:
    image: nexus.edpn.io/edpn/backend/modulith:latest-snapshot
    restart: on-failure
    env_file:
      - env/${ENVIRONMENT}/.env_modulith
    ports:
      - "8080:8080"
    healthcheck:
      test: "wget -qO- localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      kafka:
        condition: service_healthy
      trademodule_postgis:
        condition: service_healthy
      explorationmodule_postgis:
        condition: service_healthy

volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  trademodule_postgis:
    driver: local
  explorationmodule_postgis:
    driver: local
