version: "3.8"

name: "edpn-local"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper:/bitnami"
    healthcheck:
      test: nc -vz localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  kafka:
    image: "bitnami/kafka:3.4"
    restart: on-failure
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_COMPRESSION_TYPE=gzip
    volumes:
      - "kafka:/bitnami/kafka"
    ports:
      - "9092:9092"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      zookeeper:
        condition: service_healthy

  trademodule_postgres:
    image: "postgres:15-alpine"
    restart: on-failure
    environment:
      - POSTGRES_USER=edpn_trademodule
      - POSTGRES_PASSWORD=MSDVq372rNk3AwRq
      - POSTGRES_DB=trademodule
    volumes:
      - "trademodule_postgres:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  usermodule_postgres:
    image: "postgres:15-alpine"
    restart: on-failure
    environment:
      - POSTGRES_USER=edpn_usermodule
      - POSTGRES_PASSWORD=hvWYDHqG3yXCKReH
      - POSTGRES_DB=usermodule
    volumes:
      - "usermodule_postgres:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  trademodule_postgres:
    driver: local
  usermodule_postgres:
    driver: local
