version: "3.8"

name: "edpn"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    env_file:
      - .env
    volumes:
      - "zookeeper:/bitnami"

  kafka:
    image: "bitnami/kafka:3.4"
    env_file:
      - .env
    volumes:
      - "kafka:/bitnami/kafka"
    depends_on:
      - zookeeper

  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"

  mongodb:
    image: "mongo:5.0"
    env_file:
      - .env
    volumes:
      - "mongodb:/data/db"

  liquibase:
    build:
      context: ./liquibase
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

  message-listener:
    build:
      context: ./message-listener
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres
      - mongodb

  commodityv3-processor:
    build:
      context: ./message-processors
      dockerfile: dockerfile-message-processors
      args:
        - APP_DIR=commodityv3-processor
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres

  fsssignaldiscoveredv1-processor:
    build:
      context: ./message-processors
      dockerfile: dockerfile-message-processors
      args:
        - APP_DIR=fsssignaldiscoveredv1-processor
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres

  navroutev1-processor:
    build:
      context: ./message-processors
      dockerfile: dockerfile-message-processors
      args:
        - APP_DIR=navroutev1-processor
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres

  rest:
    build:
      context: ./rest
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres

volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  postgres:
    driver: local
  mongodb:
    driver: local
