version: "3.8"

name: "edpn-local"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper:/bitnami"
    healthcheck:
      test: nc -vz localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  kafka:
    image: "bitnami/kafka:3.4"
    restart: on-failure
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_COMPRESSION_TYPE=gzip
    volumes:
      - "kafka:/bitnami/kafka"
    ports:
      - "9092:9092"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      zookeeper:
        condition: service_healthy

  trademodule_postgis:
    image: "postgis/postgis:15-3.3-alpine"
    restart: on-failure
    environment:
      - POSTGRES_USER=edpn_trademodule
      - POSTGRES_PASSWORD=MSDVq372rNk3AwRq
      - POSTGRES_DB=trademodule
    volumes:
      - "trademodule_postgis:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d trademodule -U edpn_trademodule"]
      interval: 10s
      timeout: 5s
      retries: 5

  explorationmodule_postgis:
    image: "postgis/postgis:15-3.3-alpine"
    restart: on-failure
    environment:
      - POSTGRES_USER=edpn_explorationmodule
      - POSTGRES_PASSWORD=TvhRZP7b6Hrw64Ct
      - POSTGRES_DB=explorationmodule
    volumes:
      - "explorationmodule_postgis:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d explorationmodule -U edpn_explorationmodule"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  trademodule_postgis:
    driver: local
  explorationmodule_postgis:
    driver: local
