name: Branch test

on:
  push:
    branches-ignore:
      - master
      - development
permissions:
  checks: write

jobs:
  validation:
    name: "Validate, build and test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate maven wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build --refresh-dependencies
        run: ./gradlew build test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: "**/reports/*"
          retention-days: 5
